sudo: required
services:
  - docker

env:
  global:
    - COMPOSE_VERSION: 1.12.0
    - secure: W83x4IKY3XSPsxhIP6fqTZvggqPvBeZXfbC+DWQRlerir0e/7pLwaICgPrXH6fOLAmdHtOCgore0NIq8gMHO0ktyuYsqBiunIWunlDlEsHNtnZwKdDz6g8XId85/FFqv54aVHHxW310gvFfw6B2Lpu4CsWuWuWLpr/TMp+kRVktVPes57MRl6gVWm2VwJt961GmAt3snFSNK5adrYi+JElpQq1Ow1+JuB/evd1zPCfEhYY/xXDuViMo2yDmNwUtDM/MX4QT+a4mc5EIlOFsMNZLJgwLmcKa8M9wjNDwi9hePNB0Mas77aeHxvUTbGPayF0rFDdyD+g0ZMFS16OcfvtAik65CswV1TC/9jQ9LDciaIsPqpH+0ur9EWRc2NybfYVVhRocdtZ5VxWql9BzNDv991IAqIuvVNuJO6LDQ6UCI+zz/I9m7BC4Ean94Jz2HP/tqI8wftXK35bjrgMWgEOXuF8MYnfAnFeP+1Hp2aFYKs0qTfsrZDz5rCQTGksd0tmdRz1UrrGjuHQhauHvZX+Tiz0nbgRaCjFRJicIXkI/ZH/srGZsBvSJy3rsp00PsdksZ2HkZPr9hwpah5tWxA3yEsES0p+6DWUay94SvJL4XJYKcfrlav+TTlo9SgiK47pLx1V59WBB1WIY+1irVV5wh3gWQPNgHuultah/n6h0=
    - secure: KEcrIpXfepTir1baq96qF/44sBhyE6l6YNKCvGVQNamMwPgodwFD28eNbOnI2PAUqH6U8dUekUhTCMs0fUyGTSNUtFVGtDGwbvoKCgMnG8UlpcmyaVgo7xyN4UKsBdKOWQAT44VDbBY4/9/16KQoJ4t8Jod5VOt6LENhjF804YmjtCS7MW46VhuK1mD1L0voe2lPWPtc1tlBgOTQ62zgZulLmD0JilWw5PckI9zu8ZeNpNqOjAs2mYRgU6Ed5LPWSyjkBVWH11EtQsvXQKwQUynDFH3wnoeDpP3Nigi4pWOqAWr7r+A/F5pBlklANLpT49nBEMtUu9SPuqGKkdBlaCIVbd/ov3PowRg4BfDBN/o8ZAGaUcS3lBtXMYJun4e0Zq9irmtFt6rI/HYxPscInPlsafZ3ROf577F0qGtec8aRcpGzi+QAEGpTCM9uYm4PEX88ajQbRCTdD+p7FLsQCahqrFkZD2xPSR4Pt3sRCKHX5AW6/XYMcKomz4xw1bs2okWOmZWzFbGo26cMeAzpEuxwRp8o/WB7Xn9ulhUWxpBy1KBEgPBRUcK9EihTo89nabcwFDJuZTbxmRyz8HokAaW1TOZ+qIb9vtzKMP81fUr/YN59Ty926U1rdOBW21rKIDuT+jo700CRCthgQ2vTIZs5DtMW6+JautKL3wwLQuk=

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
    - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

language: php
php:
- 5.6

script:
    - echo $COMPOSE_VERSION
    - uname -s
    - uname -m
    - composer install
    - docker ps
    - cd code; composer install; cd ..
    - cd code; ./vendor/bin/codecept build; cd ..
    - cd docker/; docker-compose -f docker-compose-unittest.yml up -d; cd ..
    - docker exec -ti docker_unittestphp_1 /var/www/test/runUnitTests.sh
    - cd docker/; docker-compose -f docker-compose-unittest.yml down; cd ..
    - export TAG=`if [ "$TRAVIS_TAG" != "" ]; then echo $TRAVIS_TAG; elif [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - docker build -t opencats/opencats:$TAG .
    - cd docker/env-test; docker-compose up -d
    - docker --version
    - docker info
    - docker-compose exec php /var/www/test/runAllTests.sh
    - cd ..; cd ..; ./ci/package-code.sh

deploy:
  provider: releases
  api_key:
    secure: Srgq/VW4yoYg0yWq/llOix47MAe2EKccqxfdukxrm6fePKRRv6bVBQXH/0hhrTTn4Q6xrmVycqC36SD9/JVL684xNYBESlT4V3DpZ6vxPYeNzU2GjtoMBqGCOgjZvxpq5AGIf7gXZ9GdM4+xikBPthspCcUorg8hkLgaOQ5PPlI0dC7cdFPjQweoxAqDe6VwQ31J1MiO+DPI+69GHb/KukHkS/sjhZTMZoO0shfw5dhv0TSuaeaPzWYw1+g6sNdgNurNbi4bPEEpofUdfA+WaWw7oapsO7ZW4qTqKxsrsrCf1ZgTnynm2Kow5D7oFVqRkt/kpoQ/UzwZUalzm8JrVeYPbQ2j7mYxOh3TcTYn24NSm8xuDgF8ZaG3BxoWCLQSA8pdJZRI7QbWrDdFA93ZD1EWRW0amL3rOGLED61K0ZFhulUBy1bKyjAnT2T6FPsKk4hOwFDo1nojzemQnl6PfPT6Lsuvk5FotevsemBUQl+xx7UQsxhDM3kw3/IheE/abOYmIK+qRKdcH5J04m+dadXKZBa+h/Jsd5AdC7Yp3Si74IhJFceyvQIx7GkkG4fo/0Y34mCAXuwEN7acB7RbNU8DVyzfUtpWSPwkw2iDTJshDsV1RN94Xzt+k/GvLAvAOttozkhruYV563+MEYizBRN+96jaF/35dZYd+X3UwBA=
  file:
     - $TRAVIS_BUILD_DIR/opencats-$TRAVIS_TAG-full.tar.gz
     - $TRAVIS_BUILD_DIR/opencats-$TRAVIS_TAG-full.zip
  skip_cleanup: true
  on:
    tags: true

addons:
  artifacts:
    debug: true
    paths:
      - ./code/tests/_output
    target_paths: $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: opencats
    s3_region: us-east-1

after_success:
  - export TAG=`if [ "$TRAVIS_TAG" != "" ]; then echo $TRAVIS_TAG; elif [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push opencats/opencats:$TAG
